services:
  ui:
    build:
      context: ./docker/ui
    ports:
      - ${UI_PORT:-8080}:8080
    volumes:
      - ./gen:/openapi
    environment:
      QUERY_CONFIG_ENABLED: true

  merger:
    build:
      context: ./docker/merger
    volumes:
      - ./src:/app/src
      - ./gen:/openapi
    command: >
      npm run watch
