services:
  cli:
    build:
      context: ./docker/cli
    volumes:
      - ./gen:/openapi
      - ./docker/cli/app:/app

  ui:
    build:
      context: ./docker/ui
    ports:
      - ${UI_PORT:-8080}:8080
    volumes:
      - ./gen:/openapi
    environment:
      QUERY_CONFIG_ENABLED: true

  merger:
    build:
      context: ./docker/cli
    volumes:
      - ./docker/cli/app:/app
      - ./src:/app/src
      - ./gen:/openapi
    command: >
      ash -c '
      npm i &&
      npm run watch
      '
  
  doc:
    image: redocly/redoc:v2.1.4
    volumes:
      - ./gen:/usr/share/nginx/html/openapi
    ports:
      - ${DOC_PORT:-8081}:80
    environment:
      SPEC_URL: openapi/v1.yml
