services:
  ui:
    build:
      context: ./docker/ui
    ports:
      - ${UI_PORT:-8080}:8080
    volumes:
      - ./gen:/openapi
    environment:
      API_URL: openapi/openapi.yml

  merger:
    build:
      context: ./docker/merger
    volumes:
      - ./src:/app/src
      - ./gen:/openapi
    command: >
      npm run watch
