openapi: 3.0.0
info:
  title: Sample API
  description: >-
    Optional multiline or single-line description in
    [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0

servers:
  - url: http://api.example.com
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /v1/users/signup:
    $ref: ./paths/v1/users/signup.yml
  /v1/users/auth:
    $ref: ./paths/v1/users/auth.yml
  /v1/users/me:
    $ref: ./paths/v1/users/me.yml
  /v1/users/refresh:
    $ref: ./paths/v1/users/refresh.yml
  /v1/e/{path}:
    $ref: ./paths/v1/e/[path].yml

components:
  securitySchemes:
    bearerAuth:
      $ref: ./components/securitySchemes/bearerAuth.yml

  schemas:
    uuid:
      $ref: ./components/schemas/uuid.yml
    password:
      $ref: ./components/schemas/password.yml
    token:
      $ref: ./components/schemas/token.yml
    event.path:
      $ref: ./components/schemas/event/path.yml
    event.name:
      $ref: ./components/schemas/event/name.yml

  responses:
    UnauthorizedError:
      $ref: ./components/responses/UnauthorizedError.yml
    NotFoundError:
      $ref: ./components/responses/NotFoundError.yml
