name: Deploy Docs to S3

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  actions: write
  checks: write
  contents: write
  id-token: write

jobs:
  build:
    name: make
    uses: ./.github/workflows/make.yml
    
  deploy:
    name: Deploy Docs
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}
    
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: openapi
        path: gen

    - name: Copy docs
      run: |
       cp gen/v1.html docs/

    - name: Deploy to S3
      run: |
        echo "AWS s3 sync"
        aws s3 sync docs s3://${{ vars.AWS_S3_BUCKET }} --delete
        echo "AWS reset cloudfront"
        aws cloudfront create-invalidation --distribution-id ${{ vars.AWS_CLOUDFRONT_ID }} --paths "/*"
