name: Publish Docs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  actions: write
  checks: write
  contents: write

jobs:
  build:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Install and cache nodejs
      uses: actions/setup-node@v3
      with:
        node-version-file: package.json
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
  
    - name: Install packages
      run: npm ci

    - name: Lint file format
      run: npm run lint:fmt

    - name: Merge
      run: npm run merge:v1

    - name: Build docs
      run: npm run build-docs:v1

    - name: Copy docs
      run: cp gen/v1.html docs/

    - name: Deploy to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
