name: Publish Docs

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Install and cache nodejs
      uses: actions/setup-node@v3
      with:
        node-version-file: package.json
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    
    - name: Install packages
      run: npm ci

    - name: Lint file format
      run: npm run lint:fmt

    - name: Merge
      run: npm run merge:v1

    - name: Build docs
      run: npm run build-docs:v1

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
